#!/usr/bin/env Rscript
#Load necessary packages
library(pophelper)
library(tidyverse)
library(ggthemes)

# set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# define a color pallette with maximal contrast
ancestry.colours <- c("A"="gold2", "B"="plum4","C"= "darkorange1", 
                      "D"="lightskyblue2", "E"="firebrick","F"= "burlywood3", "G"="gray51", 
                      "H"="springgreen4", "I"="lightpink2", "J"="deepskyblue4", "WHOLE_POPULATION"="black", 
                      "K"="mediumpurple4","L"= "orange","M"= "maroon","N"= "yellow3","O"= "brown4", 
                      "P"="yellow4", "Q"="sienna4", "R"="chocolate", "S"="gray19")

# pie_chart define a color pallette with maximal contrast
ancestry.colours.pie <- c("perc_a"="gold2", "perc_b"="plum4","perc_c"= "darkorange1",
                          "perc_d"="lightskyblue2", "perc_e"="firebrick","perc_f"= "burlywood3",
                          "perc_g"="gray51",
                          "perc_h" = "springgreen4",
                          "perc_i" = "lightpink2",
                          "perc_j" = "deepskyblue4",
                          "perc_k" = "mediumpurple4",
                          "perc_l" = "orange")

# hawaii strains
strain_islands <- c("XZ1514" = "#E69F00", "XZ1516" = "#E69F00","XZ1513" = "#E69F00","ECA372" = "#E69F00","ECA701" = "#E69F00","XZ1515" = "#E69F00",
                    "CB4856" = "#56B4E9",
                    "ECA369" = "#009E73","ECA738" = "#009E73",
                    "QX1792" = "#0072B2", "QX1794" = "#0072B2", "QX1793" = "#0072B2", "QX1791" = "#0072B2", "ECA740" = "#0072B2", "ECA741" = "#0072B2", "ECA363" = "#0072B2", "ECA743" = "#0072B2", "ECA742" = "#0072B2",
                    "ECA760" = "#CC79A7","ECA768" = "#CC79A7","ECA777" = "#CC79A7","ECA706" = "#CC79A7","ECA705" = "#CC79A7","ECA703" = "#CC79A7","ECA807" = "#CC79A7","ECA778" = "#CC79A7",
                    "ECA812" = "#CC79A7","ECA710" = "#CC79A7","ECA744" = "#CC79A7","ECA745" = "#CC79A7","ECA732" = "#CC79A7","ECA733" = "#CC79A7","ECA746" = "#CC79A7","DL238" = "#CC79A7",
                    "ECA347" = "#CC79A7","ECA730" = "#CC79A7","ECA724" = "#CC79A7","ECA722" = "#CC79A7","ECA189" = "#CC79A7","ECA191" = "#CC79A7","ECA723" = "#CC79A7","ECA712" = "#CC79A7",
                    "ECA396" = "#CC79A7")

#set VCF path for system call below
VCF_PATH="data/ANNOTATE_VCF/LD_0.8.vcf.gz"

# generate input VCF for running SplitsTree
strain_vector <- paste(sort(names(strain_islands)), sep = ",", collapse = ",")
system(glue::glue("bcftools view -s {strain_vector} {VCF_PATH} -Oz -o data/ANNOTATE_VCF/Hawaii.vcf.gz"))

# Generate VCF and nexus file for just Hawaiian strains. The .nexus file is opened in SplitsTree to make neighbor joining net.
system(glue::glue("python scripts/vcf2phylip.py -i data/ANNOTATE_VCF/Hawaii.vcf.gz -m 43 --fasta --nexus --nexus-binary"))

# Load representative strains from .tsv file written by Supplemental_Figure_5.R file
representative_K_strains <- data.table::fread("data/ADMIXTURE/full/BEST_K/Hawaii_plus_RepStrains_by_K.tsv")

# write VCFs and nexus files for Ks 7-15 with representative, non-admixed strains
for(apops in unique(representative_K_strains$K_size)){
  # extract strain names corresponding to different K sizes
  koi <- dplyr::filter(representative_K_strains, K_size == apops)
  strain_vector <- paste(sort(c(as.character(koi$samples), names(strain_islands))), sep = ",", collapse = ",")
  # extract number of strain variable
  n_strains <- length(sort(c(as.character(koi$samples), names(strain_islands))))
  # Subset VCF to contain strains of interest - Hawaiian and representative strains
  system(glue::glue("bcftools view -s {strain_vector} {VCF_PATH} -Oz -o data/ANNOTATE_VCF/Hawaii_K{apops}.vcf.gz"))
  # Generate nexus file, .nexus file is used for SplitsTree
  system(glue::glue("python scripts/vcf2phylip.py -i data/ANNOTATE_VCF/Hawaii_K{apops}.vcf.gz -m {n_strains} --fasta --nexus --nexus-binary"))
}

# make admixture pie charts for Figure5 K=11, sum admix poroportions and divide by total number
# load processed ancestry generated by Supplemental_Figure_5.R script
pop_perc <- data.table::fread("data/ADMIXTURE/full/BEST_K/K11_Processed_Ancestry.tsv") %>%
  tidyr::gather(cluster, frac_cluster, -samples) %>%
  dplyr::group_by(samples) %>%
  dplyr::mutate(max_frac = max(frac_cluster)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cluster, max_frac) %>%
  dplyr::mutate(samples = factor(samples, levels = unique(samples))) %>%
  dplyr::mutate(pop_assignment = ifelse(max_frac == frac_cluster, cluster, NA)) %>%
  dplyr::group_by(samples) %>%
  tidyr::fill(pop_assignment, .direction = "down") %>%
  tidyr::fill(pop_assignment, .direction = "up") %>%
  dplyr::ungroup() %>%
  tidyr::spread(cluster, frac_cluster) %>%
  dplyr::group_by(pop_assignment) %>%
  dplyr::mutate(perc_a = sum(A)/n()*100,
                perc_b = sum(B)/n()*100,
                perc_c = sum(C)/n()*100,
                perc_d = sum(D)/n()*100,
                perc_e = sum(E)/n()*100,
                perc_f = sum(F)/n()*100,
                perc_g = sum(G)/n()*100,
                perc_h = sum(H)/n()*100,
                perc_i = sum(I)/n()*100,
                perc_j = sum(J)/n()*100,
                perc_k = sum(K)/n()*100,
                n = n())%>%
  dplyr::ungroup() %>%
  dplyr::distinct(pop_assignment, perc_a, perc_b, perc_c, perc_d, perc_e, perc_f, perc_g, perc_h, perc_i, perc_j, perc_k, n) %>%
  dplyr::group_by(pop_assignment) %>%
  dplyr::mutate(total_perc = sum( perc_a, perc_b, perc_c, perc_d, perc_e, perc_f, perc_g, perc_h, perc_i, perc_j, perc_k)) %>%
  tidyr::gather(cluster, cluster_perc, - pop_assignment, -n, -total_perc) %>%
  dplyr::mutate(cluster = factor(cluster, levels = c("perc_a", "perc_b", "perc_d", "perc_e", "perc_c", "perc_f", "perc_g", "perc_h", "perc_i", "perc_j", "perc_k", "perc_l"))) %>%
  dplyr::arrange(pop_assignment, cluster)

pop_assignment_pie_chart <- ggplot(pop_perc, aes(x="", y=cluster_perc, fill=cluster))+
  geom_bar(width = 1, stat = "identity") +
  facet_wrap(~pop_assignment) +
  coord_polar("y", start=0) +
  labs(y = "", x = "", fill = "") +
  scale_fill_manual(values = ancestry.colours.pie) +
  theme_minimal()+
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid=element_blank(),
    axis.ticks = element_blank(),
    axis.text.x=element_blank())
pop_assignment_pie_chart

ggsave(paste("plots/Figure5_pie.pdf"), width = 5, height = 5)

# Write data for neighbor-joining net K=11 and pie charts in figure 5
# fig5_data3 <- pop_perc %>%
# readr::write_csv(., "data/elife_files/fig5-data3.csv")