#!/usr/bin/env Rscript
#Load necessary packages
library(tidyverse)
library(geonames)
library(ggrepel)
library(maps)
library(geosphere)
library(FSA)

# set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# Define functions
filter_box <- function(longitude, latitude, coords) {
  between(longitude, coords[1], coords[3]) &
    between(latitude, coords[2], coords[4]) &
    !is.na(longitude)
}

scale_this <- function(x){
  (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
}

# define a color pallette with maximal contrast
ancestry.colours <- c("A"="gold2", "B"="plum4","C"= "darkorange1", 
                      "D"="lightskyblue2", "E"="firebrick","F"= "burlywood3", "G"="gray51", 
                      "H"="springgreen4", "I"="lightpink2", "J"="deepskyblue4", "WHOLE_POPULATION"="black", 
                      "K"="mediumpurple4","L"= "orange","M"= "maroon","N"= "yellow3","O"= "brown4", 
                      "P"="yellow4", "Q"="sienna4", "R"="chocolate", "S"="gray19")

# make hawaii strains list
strain_islands <- c("XZ1514" = "#E69F00", "XZ1516" = "#E69F00","XZ1513" = "#E69F00","ECA372" = "#E69F00","ECA701" = "#E69F00","XZ1515" = "#E69F00",
                    "CB4856" = "#56B4E9",
                    "ECA369" = "#009E73","ECA738" = "#009E73",
                    "QX1792" = "#0072B2", "QX1794" = "#0072B2", "QX1793" = "#0072B2", "QX1791" = "#0072B2", "ECA740" = "#0072B2", "ECA741" = "#0072B2", "ECA363" = "#0072B2", "ECA743" = "#0072B2", "ECA742" = "#0072B2",
                    "ECA760" = "#CC79A7","ECA768" = "#CC79A7","ECA777" = "#CC79A7","ECA706" = "#CC79A7","ECA705" = "#CC79A7","ECA703" = "#CC79A7","ECA807" = "#CC79A7","ECA778" = "#CC79A7",
                    "ECA812" = "#CC79A7","ECA710" = "#CC79A7","ECA744" = "#CC79A7","ECA745" = "#CC79A7","ECA732" = "#CC79A7","ECA733" = "#CC79A7","ECA746" = "#CC79A7","DL238" = "#CC79A7",
                    "ECA347" = "#CC79A7","ECA730" = "#CC79A7","ECA724" = "#CC79A7","ECA722" = "#CC79A7","ECA189" = "#CC79A7","ECA191" = "#CC79A7","ECA723" = "#CC79A7","ECA712" = "#CC79A7",
                    "ECA396" = "#CC79A7")

# load data
data1 <- data.table::fread("data/Supplemental Data 1.tsv")

# load strain names, generated by Figure7.R
sample_names <- sort(data.table::fread("data/ANNOTATE_VCF/samples.txt", header = F) %>% dplyr::pull(V1))

# process fulcrum data for variable tile plot 
# Filter cso to isolates assigned to an isotype
hm_hi1 <- data1 %>%
  dplyr::filter(!is.na(isotype)) %>%
  dplyr::select(isotype,
                strain,
                c_label,
                s_label,
                substrate = fixed_substrate,
                island,
                altitude,
                latitude,
                longitude,
                ambient_temperature,
                substrate_temperature,
                ambient_humidity,
                substrate_moisture)

# load hawaii isolates found before hawaii 2017 trip
old_hi_isolates <- data.table::fread("data/WI_strain_list.csv") %>%
  dplyr::filter(isotype %in% names(strain_islands) & !(isotype %in% hm_hi1$isotype)) %>%
  dplyr::mutate(altitude = as.numeric(NA)) %>%
  dplyr::mutate(longitude = as.numeric(longitude),
                substrate_temperature = substrate_temp,
                ambient_temperature = ambient_temp)

# join old and new hawaiian isolates
hm_hi2 <- full_join(hm_hi1, old_hi_isolates)

#set substrate to manuscript categories
substrate_merge <- c("Fruit",
                     "Rotting fruit",
                     "Nut",
                     "Rotting nut")

# Correct substrates to major categories in manuscript
hm_hi3 <- hm_hi2 %>% 
  dplyr::ungroup() %>%
  dplyr::mutate(fixed_substrate = ifelse(substrate %in% c("Rotting fruit"), "Fruit",
                                  ifelse(substrate == "Rotting flower", "Flower",
                                               ifelse(substrate %in% c("Rotting wood",
                                                                       "Rotting bark",
                                                                       "Soil",
                                                                       "Compost"), 
                                                              "Vegetation", substrate)))) %>%
  dplyr::group_by(isotype) %>%
  dplyr::select(-substrate) %>%
  dplyr::mutate(main_substrate = names(sort(summary(as.factor(fixed_substrate)), decreasing=T))[1]) %>% # find most common factor in group
  dplyr::ungroup()

#set altitude from gps except for unknown collection locations
options(geonamesUsername="katiesevans")
options(geonamesHost="api.geonames.org")
hm_hi4 <- hm_hi3 %>%
  dplyr::ungroup() %>%
  dplyr::rowwise() %>%
  dplyr::mutate(altitude = ifelse(is.na(altitude),
                                  geonames::GNsrtm3(latitude, longitude)$srtm3,
                                  altitude)
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(altitude = ifelse(isotype %in% c("CB4856", "DL238"), NA, altitude))

#set islands from gps
hm_hi4$island <- "?"
hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-158.3617,21.1968,-157.5117,21.7931)), "island"] <- "Oahu"
hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-159.9362, 21.6523, -159.1782, 22.472)), "island"] <- "Kauai"
hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-157.327, 21.0328, -156.685, 21.2574)), "island"] <- "Molokai"
hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-156.7061, 20.4712, -155.9289, 21.0743)), "island"] <- "Maui"
hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-156.1346, 18.6619, -154.6985, 20.4492)), "island"] <- "Big Island"

# Identify most common island for isotypes
hm_hi5 <- hm_hi4 %>%
  dplyr::group_by(isotype) %>%
  dplyr::mutate(main_island = names(sort(summary(as.factor(island)), decreasing=T))[1]) %>%
  dplyr::ungroup()

###########################################
# Environmental Variables Stats and Plots #
###########################################

###  Generate stats for continuous variables
# assign Hawaii isotypes
hi_only_samples <- read.csv(file = "data/fulcrum/hawaii_isotypes.csv") 

# load admix info for full 276_set for K = 11
admix <- data.table::fread("data/ADMIXTURE/full/BEST_K/K11_Processed_Ancestry.tsv") %>%
  dplyr::rename(isotype = samples) %>%
  tidyr::gather(pop, frac_pop, - isotype) %>%
  dplyr::group_by(isotype) %>%
  dplyr::mutate(max_pop_frac = max(frac_pop)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(pop, max_pop_frac) %>%
  dplyr::mutate(isotype = factor(isotype)) %>%
  dplyr::group_by(isotype) %>%
  dplyr::mutate(pop_assignment = ifelse(max_pop_frac == frac_pop, pop, NA)) %>%
  dplyr::arrange(isotype, pop_assignment) %>%
  tidyr::fill(pop_assignment) %>%
  tidyr::spread(pop, frac_pop) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(Hawaiian = ifelse(isotype %in% hi_only_samples$isotype, "TRUE", "FALSE"))

# load data frame to do stats
ass_stats <- left_join(hm_hi5, data1 %>% dplyr::filter(!is.na(isotype)) %>% dplyr::select(s_label, gridsect_number)) %>%
  dplyr::filter(!is.na(isotype)) %>%
  # Filter non-type strains from ECA189 isotype and ECA396 isotype
  dplyr::mutate(filter = case_when(
    isotype == "ECA189" & strain != "ECA189" ~ T,
    isotype == "ECA396" & strain != "ECA396" ~ T)) %>%
  dplyr::mutate(filter = ifelse(is.na(filter), F, filter)) %>%
  dplyr::filter(filter == F) %>%
  # Filter to distinct c_labels for each isotype
  dplyr::distinct(c_label, isotype, .keep_all = TRUE)

# join admix and ass_stats
ass_stats <- left_join(ass_stats, admix) %>%
  group_by(c_label) %>%
  # make artifical c_label for Hawaiian isotypes collected prior to 2017 trip
  dplyr::mutate(c_label2 = as.character(ifelse(c_label == "", row_number(), c_label))) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(c_label = c_label2)

# filter for continuous variables with only one sample for each sub population
ass_stats_cont <- ass_stats %>%
  dplyr::select(lat = latitude, long = longitude,
                c_label, gridsect_number, fixed_substrate, isotype, sub_pop = pop_assignment, altitude,
                ambient_temperature, substrate_temperature, ambient_humidity, substrate_moisture) %>%
  # Filter for one representative isotype from a c_label
  dplyr::distinct(c_label, sub_pop, .keep_all = T) %>%
  dplyr::mutate(sub_pop = factor(sub_pop)) %>%
  #dplyr::group_by(grid_num) %>%
  #dplyr::mutate(remove = ifelse(length))
  tidyr::gather(env_par, value, -lat, -long, -c_label, -gridsect_number, -fixed_substrate, -isotype, -sub_pop)

# gather data to long format for plotting
ass_stats_long <- ass_stats %>%
  dplyr::select(lat = latitude, long = longitude,
                c_label, gridsect_number, fixed_substrate, isotype, sub_pop = pop_assignment, altitude,
                ambient_temperature, substrate_temperature, ambient_humidity, substrate_moisture) %>%
  tidyr::gather(env_par, value, -lat, -long, -c_label, -gridsect_number, -fixed_substrate, -isotype, -sub_pop) %>%
  dplyr::group_by(sub_pop, env_par) %>%
  dplyr::mutate(pop_par_mean_full = mean(value, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(id = paste(lat,long,c_label,isotype))

#### Calculate distnaces among c_labels in meters for thinning dataset
# generate all pairs
pair <- apply(ass_stats_long %>%
                dplyr::filter(env_par == "altitude") %>%
                dplyr::distinct(c_label, .keep_all = T), # only need to compare c_labels for stats, not worried about retaining isotype, pop_assignment info  
              2, combn, m=2)

# extract pairs to side by side for pair matirx [c(T,F),] = odd rows.
left_pair <- as.data.frame(pair[ c(TRUE,FALSE), ]) 
right_pair <- as.data.frame(pair[ !c(TRUE,FALSE), ])
colnames(right_pair) <- paste("r", colnames(right_pair), sep = "_")

# measure distances between all pairs
dist <- cbind(left_pair,right_pair) %>%
  # assign lat and long back to numeric 
  dplyr::mutate(lat = as.double(as.character(lat)),
                long = as.double(as.character(long)),
                r_lat = as.double(as.character(r_lat)),
                r_long = as.double(as.character(r_long)),
                grid_num = as.double(as.character(gridsect_number)),
                r_grid_num = as.double(as.character(r_gridsect_number)),
                gridsect3 = ifelse(gridsect_number == 3 & r_gridsect_number == 3, TRUE, FALSE)) %>%
  # force dplyr to perform distHaversine function on rows
  dplyr::rowwise() %>%
  dplyr::mutate(distance = distHaversine(c(long, lat), c(r_long, r_lat)),
                under20meters = ifelse(distance < 20, TRUE, FALSE),
                under25meters = ifelse(distance < 25, TRUE, FALSE),
                under50meters = ifelse(distance < 50, TRUE, FALSE),
                under100meters = ifelse(distance < 100, TRUE, FALSE))

# Plot histogram of distances for all
ggplot(dist) +
  aes(x = distance,  fill = under25meters) +
  #geom_point()
  geom_histogram(binwidth = 1000)

# extract all c_labels w/ c. elegans within 20 meters of another c_label w/ c. elegans 
dist_filter <- dist %>%
  dplyr::filter(under20meters == TRUE) %>%
  dplyr::select(c_label, r_c_label) %>%
  tidyr::gather() %>%
  dplyr::distinct(value) %>%
  dplyr::rename(c_label = value)

#Group populations F,H  as non-admixed populations and average env_par for isotypes on c_labels in manually assigned <20 meter clusters
ass_stats_cont_dist_filtered_1 <- ass_stats_cont %>%
  dplyr::mutate(filter_20m = ifelse(c_label %in% dist_filter$c_label, TRUE, FALSE),
                kalopa =filter_box(ass_stats_cont$long, ass_stats_cont$lat, c(-155.454909,20.02578,-155.430115,20.049951)),
                volcano_1 =filter_box(ass_stats_cont$long, ass_stats_cont$lat, c(-155.2243537309,19.4221224043,-155.2216236884,19.424155)),   
                volcano_2 =filter_box(ass_stats_cont$long, ass_stats_cont$lat, c(-155.222287312,19.424165,-155.2195572695,19.4259669944)),
                maui = ifelse(isotype %in% c("QX1793", "QX1794"), TRUE, FALSE),
                kauai = ifelse(isotype %in% c("XZ1514", "XZ1515", "XZ1516"), TRUE, FALSE),
                geo_cluster = case_when(kalopa == T ~ "kalopa",
                                        volcano_1 == T ~ "volcano_1",
                                        volcano_2 == T ~ "volcano_2",
                                        maui == T ~ "maui",
                                        kauai == T ~ "kauai")) %>%
  dplyr::group_by(env_par, sub_pop, geo_cluster, filter_20m) %>%
  dplyr::mutate(mean_value_20m = mean(value, na.rm = T)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(value_thinned = ifelse(filter_20m == TRUE, mean_value_20m, value))

# label filtered samples for plotting 
ass_stats_long <- ass_stats_long %>%
  dplyr::mutate(filtered = ifelse(c_label %in% dist_filter$c_label, 0, 1))

# extract unique thinned values for each env_par, sub_pop, geo_cluster
ass_stats_cont_dist_filtered <- ass_stats_cont_dist_filtered_1 %>%
  dplyr::distinct(env_par, sub_pop, geo_cluster, value_thinned, .keep_all = T)

###perform multiple comparisions test using Dunn's test with pvalues adjusted with Bonferroni method.
Dunn_list_dist_filtered <- list()
for (e in 1:length(unique(ass_stats_cont_dist_filtered$env_par))){
  KM_df <- ass_stats_cont_dist_filtered %>%
    dplyr::filter(env_par == (unique(ass_stats_cont_dist_filtered$env_par)[e]))
  
  D_test <- dunnTest(KM_df$value_thinned ~ KM_df$sub_pop, method = "bonferroni") 
  Dunn_list_dist_filtered[[unique(ass_stats_cont_dist_filtered$env_par)[e]]] <- D_test
}
Dunn_list_dist_filtered

### Plotting supplemental figure env_par for admix pops
elevation_p <- ggplot(ass_stats_cont_dist_filtered %>% tidyr::spread(env_par, value_thinned)) +
  aes(x = sub_pop, y = altitude) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(x = sub_pop, y = altitude, fill = sub_pop), width = 0.25, size = 3, shape = 21) +
  theme_bw() +
  scale_fill_manual(values=c(ancestry.colours)) +
  labs(y = "Elevation (m)", x = "") +
  theme_bw() +
  theme(legend.position="none",
        plot.margin = unit(c(0,0,0,0), units = "cm"))
elevation_p

sub_temp_p <- ggplot(ass_stats_cont_dist_filtered %>% tidyr::spread(env_par, value_thinned)) +
  aes(x = sub_pop, y = substrate_temperature) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(x = sub_pop, y = substrate_temperature, fill = sub_pop), width = 0.25, size = 3, shape = 21) +
  scale_fill_manual(values=c(ancestry.colours)) +
  labs(y = "Substrate temperature (°C)", x = "") +
  theme_bw() +
  theme(legend.position="none",
        plot.margin = unit(c(0,0,0,0), units = "cm"))
sub_temp_p

Figure6B_C <- cowplot::plot_grid(elevation_p, sub_temp_p, labels = c("B", "C"))

# make long and determin order of plotting
long_admix_pops <- admix %>%
  dplyr::filter(Hawaiian == "TRUE") %>%
  tidyr::gather(cluster, frac_cluster, -isotype, -max_pop_frac, -pop_assignment, -Hawaiian) %>%
  dplyr::arrange(cluster, max_pop_frac) %>%
  dplyr::mutate(isotype = factor(isotype, levels = unique(isotype)))

# establish plot order of strains based on anc pop and max fraction
plot_order <- long_admix_pops %>%
  dplyr::filter(frac_cluster == max_pop_frac) %>%
  dplyr::arrange(cluster, -max_pop_frac) %>%
  dplyr::mutate(isotype = factor(isotype, levels = unique(isotype)))

# plot admixture
admix_plot <- long_admix_pops %>%
  dplyr::mutate(ordered_isotype = factor(isotype, levels = plot_order$isotype)) %>%
  ggplot() +
  geom_bar(stat = "identity", 
           aes(x = ordered_isotype, 
               y = frac_cluster, 
               fill = cluster)) +
  scale_fill_manual(values = ancestry.colours) +
  labs(fill = "", x = "", y = "Ancestry") +
  theme_bw() +
  theme(#axis.text.x=element_blank(),
    axis.text.x = element_text(angle = 90),
    axis.text.y=element_blank(),
    #axis.title.y = element_text(angle = 0, vjust = .5),
    axis.ticks=element_blank(),
    axis.title.x=element_blank(),
    panel.background=element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    #plot.background=element_blank(),
    plot.margin = unit(c(0,0,0,0), units = "cm"))

admix_plot_no_legend <- admix_plot +
  theme(legend.position="none",
        axis.line=element_blank(),
        plot.margin = unit(c(0,0,0,0), units = "cm"))

admix_legend <- cowplot::get_legend(admix_plot)

# plot full plot
Figure6_partial <- cowplot::plot_grid(admix_plot_no_legend, Figure6B_C, nrow = 2, labels = c("A", ""))
Figure6 <- cowplot::plot_grid(Figure6_partial, admix_legend, ncol = 2, rel_widths = c(1,.1))
Figure6

ggsave("plots/Figure6.pdf", width = 7.5, height = 5, useDingbats=FALSE)

# Write data for admixture plot
# long_admix_pops %>%
#   dplyr::mutate(ordered_isotype = factor(isotype, levels = plot_order$isotype)) %>%
#   readr::write_csv(., "data/elife_files/fig6-data1.csv")
# 
# # Write data for all environmental variables, stats were conducted on value_thinnned
# ass_stats_cont_dist_filtered %>%
#  readr::write_csv(., "data/elife_files/fig6-data2.csv")

# # p-values from statistical test
# altitude <- Dunn_list_dist_filtered[[1]]
# altitude <- altitude[[2]] %>%
#   dplyr::mutate(env_par = "altitude")
# 
# ambient_temperature <- Dunn_list_dist_filtered[[2]] 
# ambient_temperature <- ambient_temperature[[2]] %>%
#   dplyr::mutate(env_par = "ambient_temperature")
# 
# substrate_temperature <- Dunn_list_dist_filtered[[3]]
# substrate_temperature <- substrate_temperature[[2]]%>%
#   dplyr::mutate(env_par = "substrate_temperature")
# 
# ambient_humidity <- Dunn_list_dist_filtered[[4]]
# ambient_humidity <- ambient_humidity[[2]]%>%
#   dplyr::mutate(env_par = "ambient_humidity")
# 
# susbtrate_moisture <- Dunn_list_dist_filtered[[5]]
# susbtrate_moisture <- susbtrate_moisture[[2]] %>%
#   dplyr::mutate(env_par = "susbtrate_moisture")
# 
# full_p <- rbind(altitude, ambient_temperature, substrate_temperature, ambient_humidity, susbtrate_moisture) %>%
#   readr::write_csv(., "data/elife_files/fig6-data3.csv")
 