#!/usr/bin/env Rscript
#Load necessary packages
library(tidyverse)
library(geonames)
library(ggrepel)
library(maps)
library(ggthemes)
library(geosphere)
library(scatterpie)
library(legendMap)

# set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# Define functions used
filter_box <- function(longitude, latitude, coords) {
  between(longitude, coords[1], coords[3]) &
    between(latitude, coords[2], coords[4]) &
    !is.na(longitude)
}

# define a color pallette with maximal contrast
ancestry.colours <- c("A"="gold2", "B"="plum4","C"= "darkorange1", 
                      "D"="lightskyblue2", "E"="firebrick","F"= "burlywood3", "G"="gray51", 
                      "H"="springgreen4", "I"="lightpink2", "J"="deepskyblue4", "WHOLE_POPULATION"="black", 
                      "K"="mediumpurple4","L"= "orange","M"= "maroon","N"= "yellow3","O"= "brown4", 
                      "P"="yellow4", "Q"="sienna4", "R"="chocolate", "S"="gray19")

# make hawaii strains list
strain_islands <- c("XZ1514" = "#E69F00", "XZ1516" = "#E69F00","XZ1513" = "#E69F00","ECA372" = "#E69F00","ECA701" = "#E69F00","XZ1515" = "#E69F00",
                    "CB4856" = "#56B4E9",
                    "ECA369" = "#009E73","ECA738" = "#009E73",
                    "QX1792" = "#0072B2", "QX1794" = "#0072B2", "QX1793" = "#0072B2", "QX1791" = "#0072B2", "ECA740" = "#0072B2", "ECA741" = "#0072B2", "ECA363" = "#0072B2", "ECA743" = "#0072B2", "ECA742" = "#0072B2",
                    "ECA760" = "#CC79A7","ECA768" = "#CC79A7","ECA777" = "#CC79A7","ECA706" = "#CC79A7","ECA705" = "#CC79A7","ECA703" = "#CC79A7","ECA807" = "#CC79A7","ECA778" = "#CC79A7",
                    "ECA812" = "#CC79A7","ECA710" = "#CC79A7","ECA744" = "#CC79A7","ECA745" = "#CC79A7","ECA732" = "#CC79A7","ECA733" = "#CC79A7","ECA746" = "#CC79A7","DL238" = "#CC79A7",
                    "ECA347" = "#CC79A7","ECA730" = "#CC79A7","ECA724" = "#CC79A7","ECA722" = "#CC79A7","ECA189" = "#CC79A7","ECA191" = "#CC79A7","ECA723" = "#CC79A7","ECA712" = "#CC79A7",
                    "ECA396" = "#CC79A7")

# load data
data1 <- data.table::fread("data/Supplemental Data 1.tsv")

# get Hawaii strains
hi_only_samples <- read.csv(file = "data/fulcrum/hawaii_isotypes.csv") 

# load in wi strain info for lat long coordinates for map
df <- data.table::fread("data/WI_strain_list.csv")

# load strain names, generated by Figure7.R
sample_names <- sort(data.table::fread("data/ANNOTATE_VCF/samples.txt", header = F) %>% dplyr::pull(V1))

#Set K=11 as admixture qfile
k = 11
qfile <- as.data.frame(pophelper::readQ("data/ADMIXTURE/full/BEST_K/LD_0.8_MAF_0.004.11.Q"))
colnames(qfile) <- LETTERS[1:k]
qfile <- qfile %>%
  dplyr::mutate(samples = as.vector(sample_names))

# make long and determin order of plotting
long_admix_pops <- qfile %>%
  dplyr::mutate(samples = sample_names) %>%
  dplyr::filter(samples %in% names(strain_islands)) %>%
  tidyr::gather(cluster, frac_cluster, -samples) %>%
  dplyr::group_by(samples) %>%
  dplyr::mutate(max_frac = max(frac_cluster)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cluster, max_frac) %>%
  dplyr::mutate(samples = factor(samples, levels = unique(samples)))

# load admix info for full 276_set for K = 12
admix <- data.table::fread("data/ADMIXTURE/full/BEST_K/K11_Processed_Ancestry.tsv") %>%
  dplyr::rename(isotype = samples) %>%
  tidyr::gather(pop, frac_pop, - isotype) %>%
  dplyr::group_by(isotype) %>%
  dplyr::mutate(max_pop_frac = max(frac_pop)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(pop, max_pop_frac) %>%
  dplyr::mutate(isotype = factor(isotype)) %>%
  dplyr::group_by(isotype) %>%
  dplyr::mutate(pop_assignment = ifelse(max_pop_frac == frac_pop, pop, NA)) %>%
  dplyr::arrange(isotype, pop_assignment) %>%
  tidyr::fill(pop_assignment) %>%
  tidyr::spread(pop, frac_pop) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(Hawaiian = ifelse(isotype %in% hi_only_samples$isotype, "TRUE", "FALSE"))

#5 plot HI map file supplement  
strain_pops <- dplyr::filter(long_admix_pops, frac_cluster == max_frac) %>%
  dplyr::rename(strain=samples)

isolation_info <- df %>%
  #dplyr::filter(reference_strain == 1)%>%
  dplyr::select(strain = isotype, long = longitude, lat = latitude, state, country)%>%
  dplyr::filter(lat != "None")%>%
  dplyr::left_join(strain_pops,.,by="strain")%>%
  dplyr::filter(!is.na(lat)) %>%
  dplyr::distinct(strain, long, lat, .keep_all = TRUE)

# get admix
full_isolation_info <- df %>%
  #dplyr::filter(reference_strain == 1) %>%
  dplyr::select(strain, isotype, long = longitude, lat = latitude, state, country) %>%
  dplyr::filter(lat != "None") %>%
  dplyr::left_join(.,admix,by="isotype") %>%
  dplyr::distinct(isotype, long, lat, .keep_all = TRUE) %>%
  dplyr::filter(!is.na(pop_assignment))

isolation_info$lat <- as.numeric(isolation_info$lat)
isolation_info$long <- as.numeric(isolation_info$long)

# maybe need?
dev.off()
world <- map_data("world")
world <- world[world$region != "Antarctica",] # intercourse antarctica

# plot Hawaii hybrid
HW_plot <- ggplot()+ geom_map(data=world, map=world,
                              aes(x=long, y=lat, map_id=region),
                              color="black", fill="#E6E6E6", size=0.25)+
  scale_fill_manual(values = ancestry.colours,name = "Population")+
  theme_map()+
  geom_point(aes(long, lat, fill = pop_assignment),
             data=full_isolation_info %>% dplyr::filter(max_pop_frac > 0.999) %>%
               dplyr::mutate(pop_assignment = factor(pop_assignment, level = c("A", "D", "F", "G", "H", "I",
                                                                               "J", "B", "C", "E", "K"))) %>%
               dplyr::arrange(pop_assignment),
             shape = 21, size = 3) +
  theme(legend.position = "none") +
  coord_quickmap(xlim = c(-160,-155), ylim = c(19,22.3)) +  # coord_quickmap keeps correct aspect ratio: xlim = c(-160,-155), ylim = c(19,22.3)
  scale_bar(lon = -158.5, lat = 19, 
            distance_lon = 100, distance_lat = 16, distance_legend = 32, 
            dist_unit = "km", orientation = FALSE)
  HW_plot2 <- HW_plot + geom_scatterpie(aes(x=long, y=lat, r =.15),
                                     data=dplyr::filter(full_isolation_info, state == "Hawaii" & isotype %in% c("XZ1513", "XZ1515", "QX1794", "ECA372", "ECA738", "ECA189", "ECA710", "ECA743")), cols=LETTERS[1:11]) #### "XZ1513", "XZ1515", "QX1794", "ECA372", "ECA738", "ECA189",  "ECA710", "ECA743
#plot california and west coast
dev.off()
states <- map_data("state")
states <- states %>%
  filter(region %in% c("california", "oregon", "washington"))   # intercourse other states

CAL_plot <- ggplot()+ geom_map(data=states, map=states,
                               aes(x=long, y=lat, map_id=region),
                               color="black", fill="#E6E6E6", size=0.25)+
  scale_fill_manual(values = ancestry.colours,name = "Population")+
  theme_map()+
  geom_point(aes(long, lat, fill = pop_assignment),
             data=full_isolation_info %>% dplyr::filter(state %in% c("California", "Oregon", "Washington") & isotype != "QG556" & max_pop_frac > 0.99) %>%
               dplyr::mutate(pop_assignment = factor(pop_assignment, level = c("A", "D", "F", "G", "H", "I",
                                                                               "J", "B", "C", "E", "K"))) %>%
               dplyr::arrange(pop_assignment),
             shape = 21, size = 3) +
  theme(legend.position = "none") +
  coord_quickmap()  + # coord_quickmap keeps correct aspect ratio
  scale_bar(lon = -122.5, lat = 31.5, 
            distance_lon = 250, distance_lat = 40, distance_legend = 80, 
            dist_unit = "km", orientation = FALSE)
west_coast_plot <- CAL_plot + geom_scatterpie(aes(x=long, y=lat, r = .5),
                                              data=dplyr::filter(full_isolation_info, state == "California" & isotype == "QG556"), cols=LETTERS[1:11])

#put california and west coast together
hybrid_plot <- cowplot::plot_grid(HW_plot2, west_coast_plot,
                                  ncol = 2,
                                  labels = c("A", "B"),
                                  rel_widths = c(1, 1))

ggsave(hybrid_plot, filename = "plots/Supplemental Figure 7.pdf", width = 7.5, height = 5, useDingbats = FALSE)

# # Save data for ploting admix groups
# full_isolation_info %>%
# readr::write_csv(., "data/elife_files/supp-fig7-data1.csv")

# Temp
# plot Hawaii hybrid
world_plot <- ggplot()+ geom_map(data=world, map=world,
                              aes(x=long, y=lat, map_id=region),
                              color="black", fill="#E6E6E6", size=0.25)+
  scale_fill_manual(values = ancestry.colours,name = "Population")+
  theme_map()+
  geom_point(aes(long, lat, fill = pop_assignment),
             data=full_isolation_info %>% dplyr::filter(pop_assignment == "A") %>%
               dplyr::mutate(pop_assignment = factor(pop_assignment, level = c("A", "D", "F", "G", "H", "I",
                                                                               "J", "B", "C", "E", "K"))) %>%
               dplyr::arrange(pop_assignment),
             shape = 21, size = 3) +
  theme(legend.position = "none") +
  coord_quickmap()  # coord_quickmap keeps correct aspect ratio: xlim = c(-160,-155), ylim = c(19,22.3)
  scale_bar(lon = -158.5, lat = 19, 
            distance_lon = 100, distance_lat = 16, distance_legend = 32, 
            dist_unit = "km", orientation = FALSE)

world_plot2 <- world_plot + geom_scatterpie(aes(x=long, y=lat, r =5),
                                      data=dplyr::filter(full_isolation_info, A > 0.05 & pop_assignment != "A"), cols=LETTERS[1:11], alpha = 0.8) 

# filter to isotypes with > 5% pop A
popA_admixed <- full_isolation_info %>% dplyr::filter(pop_assignment == "E" ) # & pop_assignment != "A"

length(unique(popA$isotype))


