#!/usr/bin/env Rscript
#Load necessary packages
library(tidyverse)
library(geonames)
library(ggrepel)
library(maps)
library(geosphere)

# set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# Define functions used
filter_box <- function(longitude, latitude, coords) {
  between(longitude, coords[1], coords[3]) &
    between(latitude, coords[2], coords[4]) &
    !is.na(longitude)
}

# define a color pallette with maximal contrast
ancestry.colours <- c("A"="gold2", "B"="plum4","C"= "darkorange1", 
                      "D"="lightskyblue2", "E"="firebrick","F"= "burlywood3", "G"="gray51", 
                      "H"="springgreen4", "I"="lightpink2", "J"="deepskyblue4", "WHOLE_POPULATION"="black", 
                      "K"="mediumpurple4","L"= "orange","M"= "maroon","N"= "yellow3","O"= "brown4", 
                      "P"="yellow4", "Q"="sienna4", "R"="chocolate", "S"="gray19")

# make hawaii strains list
strain_islands <- c("XZ1514" = "#E69F00", "XZ1516" = "#E69F00","XZ1513" = "#E69F00","ECA372" = "#E69F00","ECA701" = "#E69F00","XZ1515" = "#E69F00",
                    "CB4856" = "#56B4E9",
                    "ECA369" = "#009E73","ECA738" = "#009E73",
                    "QX1792" = "#0072B2", "QX1794" = "#0072B2", "QX1793" = "#0072B2", "QX1791" = "#0072B2", "ECA740" = "#0072B2", "ECA741" = "#0072B2", "ECA363" = "#0072B2", "ECA743" = "#0072B2", "ECA742" = "#0072B2",
                    "ECA760" = "#CC79A7","ECA768" = "#CC79A7","ECA777" = "#CC79A7","ECA706" = "#CC79A7","ECA705" = "#CC79A7","ECA703" = "#CC79A7","ECA807" = "#CC79A7","ECA778" = "#CC79A7",
                    "ECA812" = "#CC79A7","ECA710" = "#CC79A7","ECA744" = "#CC79A7","ECA745" = "#CC79A7","ECA732" = "#CC79A7","ECA733" = "#CC79A7","ECA746" = "#CC79A7","DL238" = "#CC79A7",
                    "ECA347" = "#CC79A7","ECA730" = "#CC79A7","ECA724" = "#CC79A7","ECA722" = "#CC79A7","ECA189" = "#CC79A7","ECA191" = "#CC79A7","ECA723" = "#CC79A7","ECA712" = "#CC79A7",
                    "ECA396" = "#CC79A7")

# load data
data1 <- data.table::fread("data/Supplemental Data 1.tsv")

# load strain names, generated by Figure7.R
sample_names <- sort(data.table::fread("data/ANNOTATE_VCF/samples.txt", header = F) %>% dplyr::pull(V1))

#Set K=11 as admixture qfile
k = 11
qfile <- as.data.frame(pophelper::readQ("data/ADMIXTURE/full/BEST_K/LD_0.8_MAF_0.004.11.Q"))
colnames(qfile) <- LETTERS[1:k]
qfile <- qfile %>%
  dplyr::mutate(samples = as.vector(sample_names))

# make long and determin order of plotting
long_admix_pops <- qfile %>%
  dplyr::mutate(samples = sample_names) %>%
  tidyr::gather(cluster, frac_cluster, -samples) %>%
  dplyr::group_by(samples) %>%
  dplyr::mutate(max_frac = max(frac_cluster)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cluster, max_frac) %>%
  dplyr::mutate(samples = factor(samples, levels = unique(samples)))

# establish plot order of strains based on anc pop and max fraction
plot_order <- long_admix_pops %>%
  dplyr::filter(frac_cluster == max_frac) %>%
  dplyr::arrange(cluster, -max_frac) %>%
  dplyr::mutate(samples = factor(samples, levels = unique(samples)))

admix_plot <- long_admix_pops %>%
  dplyr::mutate(ordered_samples = factor(samples, levels = plot_order$samples)) %>%
  ggplot() +
  geom_bar(stat = "identity", 
           aes(x = ordered_samples, 
               y = frac_cluster, 
               fill = cluster)) +
  scale_fill_manual(values = ancestry.colours) +
  labs(fill = "", x = "", y = "") +
  theme_bw() +
  coord_flip() +
  theme(axis.text.x=element_blank(),
    text = element_text(size=8),
    #axis.text.x = element_text(angle = 90),
    #axis.text.y=element_blank(),
    axis.ticks=element_blank(),
    axis.title.x=element_blank(),
    panel.background=element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    #plot.background=element_blank(),
    plot.margin = unit(c(0,0,0,0), units = "cm"))

Supp_fig6A_plot <- admix_plot +
  theme(legend.position="none",
        axis.line=element_blank(),
        plot.margin = unit(c(0,0,0,0), units = "cm"))

admix_legend <- cowplot::get_legend(admix_plot)

#Plot maps  
isotype_pops <- dplyr::filter(long_admix_pops, frac_cluster == max_frac) %>%
  dplyr::rename(isotype=samples)

# load in wi strain info for lat long coordinates for map
df <- data.table::fread("data/WI_strain_list.csv")

isolation_info <- df %>%
  #dplyr::filter(reference_strain == 1)%>%
  dplyr::select(strain, isotype, long = longitude, lat = latitude, state, country)%>%
  dplyr::filter(lat != "None")%>%
  dplyr::left_join(isotype_pops,.,by="isotype")%>%
  dplyr::filter(!is.na(lat)) %>%
  dplyr::distinct(isotype, long, lat, .keep_all = TRUE)

isolation_info$lat <- as.numeric(isolation_info$lat)
isolation_info$long <- as.numeric(isolation_info$long)

# Plot Supplemental Figure 6D
dev.off()
world <- map_data("world")
world <- world[world$region != "Antarctica",] # intercourse antarctica

Supp_fig6D_plot <- ggplot()+ geom_map(data=world, map=world,
                                 aes(x=long, y=lat, map_id=region),
                                 color="black", fill="#E6E6E6", size=0.25)+
  scale_fill_manual(values = ancestry.colours,name = "Population")+
  theme_map()+
  geom_label_repel(aes(long, lat, label = isotype, fill = cluster),
                   data=dplyr::filter(isolation_info, state == "Hawaii"),
                   fontface = 'bold', color = 'white',
                   segment.color = 'cyan')+
  theme(legend.position = "none")+
  coord_quickmap(xlim = c(-160,-155), ylim = c(19,22.3)) # coord_quickmap keeps correct aspect ratio

#Plot Supplemental Figure 6A
isolation_info_full <- df %>%
  #dplyr::filter(reference_strain == 1)%>%
  dplyr::select(strain, isotype, reference_strain, long = longitude, lat = latitude, state, country)%>%
  dplyr::filter(reference_strain == 1) %>%
  #dplyr::filter(lat != "None")%>%
  dplyr::left_join(isotype_pops,.,by="isotype") #%>%
  #dplyr::filter(!is.na(lat))

isolation_info_full$lat <- as.numeric(isolation_info_full$lat)
isolation_info_full$long <- as.numeric(isolation_info_full$long)

Supp_fig6B_plot <- ggplot()+ geom_map(data=world, map=world,
                                      aes(x=long, y=lat, map_id=region),
                                      color="black", fill="#E6E6E6", size=0.25)+
  scale_fill_manual(values = ancestry.colours,name = "Population")+
  theme_map()+
  geom_point(aes(long, lat, fill = cluster),
             data=isolation_info_full %>%
               dplyr::mutate(cluster = factor(cluster, level = c("A", "B", "D",
                                                                 "G", "H", "I", "J", "K", "F", "E", "C"))) %>%
               dplyr::arrange(cluster),
             shape = 21, size = 3) +
  theme(legend.position = "none") +
  coord_quickmap()

# 7 plot euro map
Supp_fig6C_plot <- ggplot()+ geom_map(data=world, map=world,
                                aes(x=long, y=lat, map_id=region),
                                color="black", fill="#E6E6E6", size=0.25)+
  scale_fill_manual(values = ancestry.colours,name = "Population")+
  theme_map()+
  geom_point(aes(long, lat, fill = cluster),
             data=isolation_info_full %>%
               dplyr::mutate(cluster = factor(cluster, level = c("A", "B", "D",
                                                                 "G", "H", "I", "J", "K", "F", "E", "C"))) %>%
               dplyr::arrange(cluster),
             shape = 21, size = 2.5) +
  theme(legend.position = "none") +
  coord_quickmap(xlim = c(-10, 39), ylim = c(35, 71))

# Make full plot
legend_europe_plot <- cowplot::plot_grid(admix_legend, Supp_fig6C_plot, labels = c("", "C"))

stack_maps <- cowplot::plot_grid(Supp_fig6B_plot, legend_europe_plot, Supp_fig6D_plot, ncol = 1, nrow = 3, rel_heights = c(.25, .25, .6), labels = c("B", "", "D"))

Supp_fig6_plot <- cowplot::plot_grid(Supp_fig6A_plot, stack_maps, ncol = 2, rel_widths = c(.2, 1), labels = c("A", ""))

ggsave(Supp_fig6_plot, filename = "plots/Supplemental Figure 6.pdf", useDingbats = F,
       height = 10.5,
       width = 7.5)

# Save data for ploting admix groups
  # df %>%
  # #dplyr::filter(reference_strain == 1)%>%
  # dplyr::select(strain, isotype, reference_strain, long = longitude, lat = latitude, state, country)%>%
  # #dplyr::filter(lat != "None")%>%
  # dplyr::left_join(isotype_pops,.,by="isotype")%>%
  # dplyr::select(-frac_cluster) %>%
  # dplyr::rename(max_fraction_admix_cluster_k11 = max_frac, admix_cluster_k11 = cluster) %>%
  # readr::write_csv(., "data/elife_files/supp-fig6-data1.csv")

# Save data for plotting K=11 full admixture
# supp_fig6_data2 <- long_admix_pops %>%
#   dplyr::mutate(ordered_samples = factor(samples, levels = plot_order$samples)) %>%
#   dplyr::rename(isotypes = ordered_samples) %>%
#   dplyr::select(-samples) %>%
#   readr::write_csv(., "data/elife_files/supp-fig6-data2.csv")
  